<?php
// $Id: xoops_version.php,v 2.09 2008/06/10 15:04:00 wishcraft Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Simon Roberts (AKA wishcraft)                                     //
// URL: http://www.chronolabs.org.au                                         //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //

$modversion['name'] = _XA_REAGGREGATOR_NAME;
$modversion['version'] = 2.52;
$modversion['releasedate'] = "Thursday: 28 July 2010";
$modversion['description'] = _XA_REAGGREGATOR_DESC;
$modversion['author'] = "Wishcraft";
$modversion['credits'] = "Chronolabs International";
$modversion['help'] = "xreaggregator.html";
$modversion['license'] = "GPL";
$modversion['official'] = 1;
$modversion['image'] = "images/xreaggregator_slogo.png";
$modversion['dirname'] = "xreaggregator";

$modversion['author_realname'] = "Simon Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.org.au";
$modversion['author_website_name'] = "Chronolabs Australia";
$modversion['author_email'] = "simon@chronolabs.coop";
$modversion['demo_site_url'] = "Chronolabs Australia";
$modversion['demo_site_name'] = "http://www.chronolabs.org.au/modules/xreaggregator/";
$modversion['support_site_url'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=19";
$modversion['support_site_name'] = "Chronolabs";
$modversion['submit_bug'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=19";
$modversion['submit_feature'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=19";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xreaggregator";
$modversion['tables'][1] = "xreaggregator_mashables";
$modversion['tables'][3] = "xreaggregator_categories";

$modversion['onUpdate'] = "include/update.php";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "xreaggregator.php";
$modversion['blocks'][1]['name'] = _XA_REAGGREGATOR_BNAME;
$modversion['blocks'][1]['description'] = "Shows Aggregates news via RDF/RSS news feed then re-aggregates them via RSS";
$modversion['blocks'][1]['show_func'] = 'B_XREAGGREGATOR_SHOW';
$modversion['blocks'][1]['edit_func'] = 'B_XREAGGREGATOR_EDIT';
$modversion['blocks'][1]['template'] = 'xreaggregator_block_rss.html';

// Backend RSS Feed  
// Please note **** Module Developers ****  
// this will be a new clause in module installations.  
$modversion['hasRss'] = 1;  
$modversion['rss']['rss_func'][0] = "xreaggregator_backend";  
$modversion['rss']['rss_file'][0] = "include/collaboration_feed.php";  

// Backend Sitemap Feed  
// Please note **** Module Developers ****   
// this will be a new clause in module installations.  
$modversion['hasSitemap'] = 1;  
$modversion['sitemap']['sitemap_func'][0] = "xreaggregator_sitemap";  
$modversion['sitemap']['sitemap_file'][0] = "include/collaboration_feed.php";  
$modversion['sitemap']['sitemap_agent'][0] = "all";

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'xreaggregator_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xreaggregator_feed.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'xreaggregator_rss.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'xreaggregator_categories.html';
$modversion['templates'][4]['description'] = '';

$i=0;
$modversion['config'][$i]['name'] = 'support_multisite';
$modversion['config'][$i]['title'] = "_XA_SUPPORTMULTISITE";
$modversion['config'][$i]['description'] = "_XA_SUPPORTMULTISITE_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;

$i=sizeof($modversion['config'])+1;
$modversion['config'][$i]['name'] = 'htaccess';
$modversion['config'][$i]['title'] = "_XA_HTACCESS";
$modversion['config'][$i]['description'] = "_XA_HTACCESS_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 0;

$i=sizeof($modversion['config'])+1;
$modversion['config'][$i]['name'] = 'baseurl';
$modversion['config'][$i]['title'] = "_XA_BASEURL";
$modversion['config'][$i]['description'] = "_XA_BASEURL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'headlines';

$i=sizeof($modversion['config'])+1;
$modversion['config'][$i]['name'] = 'endofurl';
$modversion['config'][$i]['title'] = "_XA_ENDOFURL";
$modversion['config'][$i]['description'] = "_XA_ENDOFURL_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '.html';

$i=sizeof($modversion['config'])+1;
$modversion['config'][$i]['name'] = 'endofurl_rss';
$modversion['config'][$i]['title'] = "_XA_ENDOFURLRSS";
$modversion['config'][$i]['description'] = "_XA_ENDOFURLRSS_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '.rss';
	
$modversion['config'][] = array(
	'name' => 'docache',
	'title' => '_XA_CACHEME',
	'description' => '_XA_CACHEME_DESC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 1);
	
$modversion['config'][] = array(
	'name' => 'rss_utf8',
	'title' => '_XA_RSS_UTF8',
	'description' => '_XA_RSS_UTF8_DESC',
	'formtype' => 'text',
	'valuetype' => 'text',
	'default' => 'UTF-8');
	
$modversion['config'][] = array(
	'name' => 'rss_cachetime',
	'title' => '_XA_RSS_CACHETIME',
	'description' => '_XA_RSS_CACHETIME_DESC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 30,
	'options' => array('10' => 10, '20' => 20, '30' => 30, '50' => 50, '70' => 70, '90' => 90, '110' => 110));
		
$modversion['config'][] = array(
	'name' => 'snoop_quantity',
	'title' => '_XA_SNOOP_QUANTITY',
	'description' => '_XA_SNOOP_QUANTITY_DESC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 2,
	'options' => array('1' => 1, '2' => 2, '3' => 3, '5' => 5, '7' => 7, '9' => 9, '10' => 10));
	
$modversion['config'][] = array(
	'name' => 'get_method',
	'title' => '_XA_GET_METHOD',
	'description' => '_XA_GET_METHOD_DESC',
	'formtype' => 'select',
	'valuetype' => 'text',
	'default' => 'fopen',
	'options' => array('fopen' => 'fopen method', 'curl' => 'cURL (Requires Extension)'));
	
$modversion['config'][] = array(
	'name' => 'user_agent',
	'title' => '_XA_FOPEN_AGENT',
	'description' => '_XA_FOPEN_AGENT_DESC',
	'formtype' => 'text',
	'valuetype' => 'text',
	'default' => 'Mozilla/5.0 (X11; U; Linux i686; pl-PL; rv:1.9.0.2) XOOPS/20030101 XReaggregator/2.xx (php) Firefox/3.8');
?>