<?php
// $Id: xoops_version.php,v 2.09 2008/06/10 15:04:00 wishcraft Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Simon Roberts (AKA wishcraft)                                     //
// URL: http://www.chronolabs.org.au                                         //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //

$modversion['name'] = _XA_REAGGREGATOR_NAME;
$modversion['version'] = 2.09;
$modversion['releasedate'] = "Mon: 14 July 2008";
$modversion['description'] = _XA_REAGGREGATOR_DESC;
$modversion['author'] = "Based on Kazumi Ono (jp) xreaggregators by wishcraft";
$modversion['credits'] = "Chronolabs International";
$modversion['help'] = "xreaggregator.html";
$modversion['license'] = "MIT see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "images/xreaggregator_slogo.png";
$modversion['dirname'] = "xreaggregator";

$modversion['author_realname'] = "Simon Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.org.au";
$modversion['author_website_name'] = "Chronolabs Australia";
$modversion['author_email'] = "simon@chronolabs.org.au";
$modversion['demo_site_url'] = "Chronolabs Australia";
$modversion['demo_site_name'] = "http://www.chronolabs.org.au/modules/xreaggregator/";
$modversion['support_site_url'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=19";
$modversion['support_site_name'] = "Chronolabs";
$modversion['submit_bug'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=19";
$modversion['submit_feature'] = "http://www.chronolabs.org.au/forums/viewforum.php?forum=19";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "xreaggregator";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file'] = "xreaggregator.php";
$modversion['blocks'][1]['name'] = _XA_REAGGREGATOR_BNAME;
$modversion['blocks'][1]['description'] = "Shows Aggregates news via RDF/RSS news feed then re-aggregates them via RSS";
$modversion['blocks'][1]['show_func'] = 'b_xreaggregator_show';
$modversion['blocks'][1]['template'] = 'xreaggregator_block_rss.html';

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'xreaggregator_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'xreaggregator_feed.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'xreaggregator_rss.html';
$modversion['templates'][3]['description'] = '';

$modversion['config'][] = array(
	'name' => 'htaccess',
	'title' => '_XA_HTACCESS',
	'description' => '_XA_HTACCESS_DESC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 0);
	
$modversion['config'][] = array(
	'name' => 'docache',
	'title' => '_XA_CACHEME',
	'description' => '_XA_CACHEME_DESC',
	'formtype' => 'yesno',
	'valuetype' => 'int',
	'default' => 1);
	
$modversion['config'][] = array(
	'name' => 'rss_utf8',
	'title' => '_XA_RSS_UTF8',
	'description' => '_XA_RSS_UTF8_DESC',
	'formtype' => 'text',
	'valuetype' => 'text',
	'default' => 'UTF-8');
	
$modversion['config'][] = array(
	'name' => 'rss_cachetime',
	'title' => '_XA_RSS_CACHETIME',
	'description' => '_XA_RSS_CACHETIME_DESC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 30,
	'options' => array('10' => 10, '20' => 20, '30' => 30, '50' => 50, '70' => 70, '90' => 90, '110' => 110));
		
$modversion['config'][] = array(
	'name' => 'snoop_quantity',
	'title' => '_XA_SNOOP_QUANTITY',
	'description' => '_XA_SNOOP_QUANTITY_DESC',
	'formtype' => 'select',
	'valuetype' => 'int',
	'default' => 2,
	'options' => array('1' => 1, '2' => 2, '3' => 3, '5' => 5, '7' => 7, '9' => 9, '10' => 10));
	
?>